"""The contract surface as USER projects import it.

The contracts themselves live in ``mbt-adapter-base``, versioned independently
(TSD §2, FR-ADPT-01, ADR-15 §1). This module re-exports them.

**What changed in v5 (C-6).** The review's deletion test is right that core had
no business importing through here: 36 core files went via ``mbt.contracts``
and 54 went to ``mbt_adapter_base`` directly, for no reason anyone could state,
and ``from mbt_adapter_base import *`` made jump-to-definition unreliable - which
costs an agent reading the tree more than it costs a human with an IDE index.
Both are fixed: **core imports from ``mbt_adapter_base`` directly**, and the
re-export below is explicit rather than a star.

**What did not change, and why.** The review proposed deleting this module
outright, on the grounds that the rewrite is mechanical. It is mechanical
*inside this repo* - but not outside it. ``from mbt.contracts import
TestResult`` is the line ``mbt init`` stamps into every scaffolded project's
``tests/test_data_quality.py``, and it is what
``docs/spec-reference.md`` tells users to write in their own data tests. So it
is not migration scaffolding that outlived its migration; it is the public
import path for user code, and deleting it would break every existing project.

That makes ADR-15 §1 only half-superseded: its stated reason (skipping a
mid-project extraction) has indeed expired, but the module earned a second,
better reason in the meantime. This docstring is that reason, so the next
reviewer does not have to rediscover it.
"""

from mbt_adapter_base import (
    AUTO,
    CONTRACT_VERSION,
    MISSING_LEVEL,
    OTHER_LEVEL,
    OUT_OF_TIME_SPLIT,
    AdapterPlugin,
    AdapterRef,
    ArtifactRef,
    ArtifactStore,
    BinningSpec,
    BootstrapDelta,
    CapSpec,
    CategoricalPolicy,
    CheckSpec,
    ComputeAdapter,
    CustomBinning,
    DataAdapter,
    DatasetHandle,
    DatasetLocator,
    DatasetProfile,
    DatasetSpec,
    DeterminismTier,
    DriftColumn,
    DriftReport,
    EvaluationProtocol,
    EvaluationSpec,
    EventSink,
    ExposureSpec,
    FeatureSelection,
    FeatureShiftSpec,
    FeatureTransform,
    FixedWidthBinning,
    GatePeriod,
    GateSpec,
    GroundTruthLabelSpec,
    GroundTruthSpec,
    HookContext,
    JobHandle,
    JobResult,
    LabelSpec,
    ManifestNode,
    Materialization,
    MaterializedDatasetHandle,
    MetricResults,
    MetricSpec,
    ModelSpec,
    ModelVersion,
    MonitorGateSpec,
    MonitorsSpec,
    MonitorStats,
    MonotonicDirection,
    PeriodCell,
    PredictionRunInfo,
    PredictionShiftSpec,
    PredictionsReport,
    PredictionStore,
    QuantileBinning,
    RegistrationSpec,
    RegistryAdapter,
    ReportingEngine,
    ReportPeriod,
    ReportSpec,
    ReportSummary,
    RunContext,
    RunHandle,
    ScoringInputSpec,
    ScoringOutputSpec,
    ScoringSpec,
    SearchDimension,
    ShiftStat,
    SourceGroup,
    SourceTable,
    SplitSpec,
    SplitStrategy,
    StabilityCell,
    StabilityReport,
    StabilitySpec,
    Stage,
    SupportsExplain,
    SupportsFeatureImportance,
    SupportsShapImportance,
    SupportsTrainWithReport,
    TaskSchema,
    TaskType,
    TestResult,
    TopPercentBinning,
    TrackingAdapter,
    TrainedModel,
    TrainingAdapter,
    TrainingJob,
    TuningEngine,
    TuningObjective,
    TuningResult,
    TuningSpec,
    ValidationIssue,
    combine_snapshots,
    parse_time_offset,
    retry_with_jitter,
    write_materialization_metadata,
)
from mbt_adapter_base.protocols import (
    DataBuildContext,
    PythonDataTest,
    SourceTableLike,
)

__all__ = [
    "AUTO",
    "CONTRACT_VERSION",
    "MISSING_LEVEL",
    "OTHER_LEVEL",
    "OUT_OF_TIME_SPLIT",
    "AdapterPlugin",
    "AdapterRef",
    "ArtifactRef",
    "ArtifactStore",
    "BinningSpec",
    "BootstrapDelta",
    "CapSpec",
    "CategoricalPolicy",
    "CheckSpec",
    "ComputeAdapter",
    "CustomBinning",
    "DataAdapter",
    "DataBuildContext",
    "DatasetHandle",
    "DatasetLocator",
    "DatasetProfile",
    "DatasetSpec",
    "DeterminismTier",
    "DriftColumn",
    "DriftReport",
    "EvaluationProtocol",
    "EvaluationSpec",
    "EventSink",
    "ExposureSpec",
    "FeatureSelection",
    "FeatureShiftSpec",
    "FeatureTransform",
    "FixedWidthBinning",
    "GatePeriod",
    "GateSpec",
    "GroundTruthLabelSpec",
    "GroundTruthSpec",
    "HookContext",
    "JobHandle",
    "JobResult",
    "LabelSpec",
    "ManifestNode",
    "Materialization",
    "MaterializedDatasetHandle",
    "MetricResults",
    "MetricSpec",
    "ModelSpec",
    "ModelVersion",
    "MonitorGateSpec",
    "MonitorStats",
    "MonitorsSpec",
    "MonotonicDirection",
    "PeriodCell",
    "PredictionRunInfo",
    "PredictionShiftSpec",
    "PredictionStore",
    "PredictionsReport",
    "PythonDataTest",
    "QuantileBinning",
    "RegistrationSpec",
    "RegistryAdapter",
    "ReportPeriod",
    "ReportSpec",
    "ReportSummary",
    "ReportingEngine",
    "RunContext",
    "RunHandle",
    "ScoringInputSpec",
    "ScoringOutputSpec",
    "ScoringSpec",
    "SearchDimension",
    "ShiftStat",
    "SourceGroup",
    "SourceTable",
    "SourceTableLike",
    "SplitSpec",
    "SplitStrategy",
    "StabilityCell",
    "StabilityReport",
    "StabilitySpec",
    "Stage",
    "SupportsExplain",
    "SupportsFeatureImportance",
    "SupportsShapImportance",
    "SupportsTrainWithReport",
    "TaskSchema",
    "TaskType",
    "TestResult",
    "TopPercentBinning",
    "TrackingAdapter",
    "TrainedModel",
    "TrainingAdapter",
    "TrainingJob",
    "TuningEngine",
    "TuningObjective",
    "TuningResult",
    "TuningSpec",
    "ValidationIssue",
    "combine_snapshots",
    "parse_time_offset",
    "retry_with_jitter",
    "write_materialization_metadata",
]
