#!/usr/bin/env bash
# Resolve image-extras.in into the committed image-extras.txt closure.
#
# Why this exists: the runner image pins its base by digest and constrains
# every mbt dependency from uv.lock, but evidently and jupyterlab are not mbt
# dependencies, so nothing pinned THEIR transitive closure - the image build
# resolved it fresh against PyPI on every build. On 2026-08-27 that closure
# picked up statsmodels 0.15.0, released four hours earlier with macOS and
# Windows wheels only (the cp311 manylinux wheel followed at 14:30 UTC; the
# nightly ran at 14:12), so pip fell back to the sdist and hit an image that
# ships no compiler by design. The nightly live tier went red for a reason
# that had nothing to do with this repo and would have cleared itself.
#
# Resolution happens HERE, deliberately, and the answer is committed. The
# image build then installs a fixed set of versions no matter what PyPI
# published that morning.
#
# The closure is resolved AGAINST uv.lock's pins, so shared packages (numpy,
# pandas, scikit-learn, scipy, ...) come out identical in both files rather
# than as conflicting constraints. tests/test_showcase_image_pins.py asserts
# that agreement holds, so a uv.lock bump that invalidates this file fails the
# fast suite instead of a docker build.
#
# --universal: the image is built for whatever the builder's platform is
# (arm64 on a developer Mac, x86_64 in CI), so the closure carries markers for
# both rather than baking one in.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
RUNNER_DIR="$REPO_ROOT/examples/showcase/images/runner"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# The same constraint set the Dockerfile installs under: uv.lock, with the dev
# fork's JVM pins swapped for the sparkling fork's (build_image.sh does this
# transform too - keep the two in step).
echo "==> exporting uv.lock pins"
(cd "$REPO_ROOT" && uv export --frozen --no-emit-workspace --no-hashes --no-annotate --no-header \
    -o "$WORK/constraints-full.txt" >/dev/null)
grep -vE '^(pyspark|h2o|h2o-pysparkling-3-5)==' "$WORK/constraints-full.txt" > "$WORK/constraints.txt"
{
    grep -E '^(PYSPARK_PIN|H2O_PIN|PYSPARKLING_PIN)=' "$REPO_ROOT/examples/showcase/scripts/build_image.sh" \
        | sed -E 's/^[A-Z0-9_]+="([^"]+)"/\1/'
} >> "$WORK/constraints.txt"

echo "==> resolving image-extras.in against those pins"
(cd "$REPO_ROOT" && uv pip compile "$RUNNER_DIR/image-extras.in" \
    --universal --python-version 3.11 \
    --constraint "$WORK/constraints.txt" \
    --no-header --no-annotate \
    -o "$WORK/resolved.txt" >/dev/null)

{
    echo "# GENERATED by examples/showcase/scripts/lock_image_extras.sh - do not hand-edit."
    echo "#"
    echo "# The resolved closure of image-extras.in, pinned so the runner image build"
    echo "# does not depend on what PyPI published that morning. Edit image-extras.in"
    echo "# and re-run the script; see its header for why this is committed."
    echo "#"
    echo "# Resolved against uv.lock's pins, so shared packages match constraints.txt"
    echo "# exactly - tests/test_showcase_image_pins.py holds that agreement, and a"
    echo "# uv.lock bump that breaks it fails the fast suite, not a docker build."
    cat "$WORK/resolved.txt"
} > "$RUNNER_DIR/image-extras.txt"

echo "==> wrote $(grep -cE '^[a-zA-Z0-9]' "$RUNNER_DIR/image-extras.txt") pins to image-extras.txt"
