"""docs/cli-reference.md must document the actual CLI surface (a doc-drift guard).

In the spirit of the NFR-04 import guard and the repo-litter conftest guard,
this turns a one-time doc review into a permanent check: a command or flag
added to the CLI without a matching entry in docs/cli-reference.md fails here,
so the reference cannot silently rot behind the code.
"""

from pathlib import Path

import click
import typer

from mbt.cli.main import app

REPO_ROOT = Path(__file__).resolve().parent.parent
CLI_REFERENCE = (REPO_ROOT / "docs" / "cli-reference.md").read_text()

# Auto-generated by typer/click; not part of the documented product surface.
_BOILERPLATE_FLAGS = {"--help", "--install-completion", "--show-completion"}


def _cli_surface() -> tuple[set[str], set[str]]:
    root = typer.main.get_command(app)
    commands = set(root.commands)
    params = list(root.get_params(click.Context(root)))
    for command in root.commands.values():
        params += command.get_params(click.Context(command))
    flags = {
        opt
        for param in params
        for opt in getattr(param, "opts", []) + getattr(param, "secondary_opts", [])
        if opt.startswith("--")
    }
    return commands, flags - _BOILERPLATE_FLAGS


def test_cli_reference_documents_every_command() -> None:
    commands, _ = _cli_surface()
    missing = sorted(name for name in commands if f"mbt {name}" not in CLI_REFERENCE)
    assert not missing, f"commands absent from docs/cli-reference.md: {missing}"


def test_cli_reference_documents_every_flag() -> None:
    _, flags = _cli_surface()
    missing = sorted(flag for flag in flags if flag not in CLI_REFERENCE)
    assert not missing, f"flags absent from docs/cli-reference.md: {missing}"
