"""Typed events and their sinks (TSD §16, NFR-06)."""

from mbt.events.bus import EventBus, get_bus, set_bus
from mbt.events.models import (
    AdapterWarning,
    ArtifactRegistered,
    AutoResolved,
    CheckEvaluated,
    CompileCompleted,
    CompileStarted,
    Event,
    GateEvaluated,
    JobLine,
    LogMessage,
    NodeFinished,
    NodeStarted,
    ParseCompleted,
    ParseStarted,
    PromotionApplied,
    RunFinished,
    RunStarted,
    StageTransitioned,
    StateDiffed,
    TestEvaluated,
)
from mbt.events.otel import OTelSpanSink
from mbt.events.sinks import ConsoleSink, JsonLinesSink, NullSink

__all__ = [
    "AdapterWarning",
    "ArtifactRegistered",
    "AutoResolved",
    "CheckEvaluated",
    "CompileCompleted",
    "CompileStarted",
    "ConsoleSink",
    "Event",
    "EventBus",
    "GateEvaluated",
    "JobLine",
    "JsonLinesSink",
    "LogMessage",
    "NodeFinished",
    "NodeStarted",
    "NullSink",
    "OTelSpanSink",
    "ParseCompleted",
    "ParseStarted",
    "PromotionApplied",
    "RunFinished",
    "RunStarted",
    "StageTransitioned",
    "StateDiffed",
    "TestEvaluated",
    "get_bus",
    "set_bus",
]
