repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, "{extends: relaxed, rules: {line-length: {max: 120}}}"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: mbt-parse
        name: mbt parse
        entry: mbt parse
        language: system
        pass_filenames: false
        files: '\.(yml|yaml|py)$'
