"""mbt-adapter-base: the versioned contract surface between mbt-core and adapters.

Everything an adapter needs to implement or exchange with mbt lives here:
common enums, resource spec schemas, interchange types, adapter Protocols,
and the compliance test suite (``mbt_adapter_base.compliance``).
"""

from mbt_adapter_base.interchange import (
    ArtifactRef,
    DatasetLocator,
    DatasetProfile,
    DeterminismTier,
    HookContext,
    JobResult,
    ManifestNode,
    MetricResults,
    ModelVersion,
    RunContext,
    RunHandle,
    TestResult,
    TrainingJob,
    TuningResult,
    ValidationIssue,
)
from mbt_adapter_base.protocols import (
    AdapterPlugin,
    ArtifactStore,
    ComputeAdapter,
    DataAdapter,
    DatasetHandle,
    EventSink,
    JobHandle,
    RegistryAdapter,
    TaskSchema,
    TrackingAdapter,
    TrainedModel,
    TrainingAdapter,
    TuningEngine,
)
from mbt_adapter_base.specs import (
    AdapterRef,
    CheckSpec,
    DatasetSpec,
    EvaluationProtocol,
    EvaluationSpec,
    ExposureSpec,
    FeatureSelection,
    GateSpec,
    LabelSpec,
    MetricSpec,
    ModelSpec,
    RegistrationSpec,
    SearchDimension,
    SourceGroup,
    SourceTable,
    SplitSpec,
    TuningObjective,
    TuningSpec,
)
from mbt_adapter_base.types import (
    AUTO,
    CONTRACT_VERSION,
    Materialization,
    SplitStrategy,
    Stage,
    TaskType,
)

__version__ = "0.1.0"

__all__ = [
    "AUTO",
    "CONTRACT_VERSION",
    "AdapterPlugin",
    "AdapterRef",
    "ArtifactRef",
    "ArtifactStore",
    "CheckSpec",
    "ComputeAdapter",
    "DataAdapter",
    "DatasetHandle",
    "DatasetLocator",
    "DatasetProfile",
    "DatasetSpec",
    "DeterminismTier",
    "EvaluationProtocol",
    "EvaluationSpec",
    "EventSink",
    "ExposureSpec",
    "FeatureSelection",
    "GateSpec",
    "HookContext",
    "JobHandle",
    "JobResult",
    "LabelSpec",
    "ManifestNode",
    "Materialization",
    "MetricResults",
    "MetricSpec",
    "ModelSpec",
    "ModelVersion",
    "RegistrationSpec",
    "RegistryAdapter",
    "RunContext",
    "RunHandle",
    "SearchDimension",
    "SourceGroup",
    "SourceTable",
    "SplitSpec",
    "SplitStrategy",
    "Stage",
    "TaskSchema",
    "TaskType",
    "TestResult",
    "TrackingAdapter",
    "TrainedModel",
    "TrainingAdapter",
    "TrainingJob",
    "TuningEngine",
    "TuningObjective",
    "TuningResult",
    "TuningSpec",
    "ValidationIssue",
]
