"""
Auto-generated by MBT. Do not edit.
Pipeline: serving_churn_model_v1
Target: docker
"""

from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta

default_args = {
    "owner": "de-team",
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="serving_churn_model_v1",
    default_args=default_args,
    schedule="@daily",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["mbt", "serving_churn_model_v1"],
) as dag:

    load_scoring_data = BashOperator(
        task_id="load_scoring_data",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline serving_churn_model_v1"
            " --step load_scoring_data"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    load_model = BashOperator(
        task_id="load_model",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline serving_churn_model_v1"
            " --step load_model"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    apply_transforms = BashOperator(
        task_id="apply_transforms",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline serving_churn_model_v1"
            " --step apply_transforms"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    predict = BashOperator(
        task_id="predict",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline serving_churn_model_v1"
            " --step predict"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    publish = BashOperator(
        task_id="publish",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline serving_churn_model_v1"
            " --step publish"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    # Dependencies
    load_scoring_data >> apply_transforms
    load_model >> apply_transforms
    apply_transforms >> predict
    predict >> publish
