"""
Auto-generated by MBT. Do not edit.
Pipeline: training_churn_model_v1
Target: docker
"""

from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta

default_args = {
    "owner": "de-team",
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="training_churn_model_v1",
    default_args=default_args,
    schedule="@daily",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["mbt", "training_churn_model_v1"],
) as dag:

    load_data = BashOperator(
        task_id="load_data",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline training_churn_model_v1"
            " --step load_data"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    split_data = BashOperator(
        task_id="split_data",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline training_churn_model_v1"
            " --step split_data"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    train_model = BashOperator(
        task_id="train_model",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline training_churn_model_v1"
            " --step train_model"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    evaluate = BashOperator(
        task_id="evaluate",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline training_churn_model_v1"
            " --step evaluate"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    log_run = BashOperator(
        task_id="log_run",
        bash_command=(
            "cd /opt/airflow/project &&"
            " mbt step execute"
            " --pipeline training_churn_model_v1"
            " --step log_run"
            " --target docker"
            ' --run-id "run_{{ ds_nodash }}_{{ ts_nodash }}"'
        ),
    )

    # Dependencies
    load_data >> split_data
    split_data >> train_model
    train_model >> evaluate
    evaluate >> log_run
